package dev.evestaticmapplanner.localization.en

import dev.evestaticmapplanner.localization.PreferencesText

internal fun englishPreferenceText(id: PreferencesText, arguments: Array<out Any>): String = when (id) {
    PreferencesText.RESET_ALL -> "Reset All Preferences"
    PreferencesText.CATEGORY_MAP_DISPLAY, PreferencesText.MAP_DISPLAY -> "Map Display"
    PreferencesText.CATEGORY_AI_FEATURES -> "AI Features"
    PreferencesText.CATEGORY_FEATURE_PACKS, PreferencesText.FEATURE_PACKS -> "Feature Packs"
    PreferencesText.CATEGORY_OVERLAYS -> "Overlays"
    PreferencesText.CATEGORY_WEB_PACK, PreferencesText.WEB_PACK -> "Web Pack"
    PreferencesText.CATEGORY_SHARED_MAP, PreferencesText.SHARED_MAP -> "Shared Map"
    PreferencesText.EMBEDDED_ASSISTANT -> "Embedded Assistant"
    PreferencesText.AI_MODEL -> "AI Model"
    PreferencesText.WEB_SEARCH -> "Web Search"
    PreferencesText.VOICE_IO -> "Voice I/O"
    PreferencesText.MCP_INTEGRATION -> "MCP Integration"
    PreferencesText.VOICE_INPUT -> "Voice Input"
    PreferencesText.PUSH_TO_TALK_SHORTCUT -> "Push-to-Talk Shortcut"
    PreferencesText.SHORTCUT_NOT_SET -> "Not set"
    PreferencesText.SET_SHORTCUT -> "Set Shortcut"
    PreferencesText.CLEAR_SHORTCUT -> "Clear"
    PreferencesText.PRESS_SHORTCUT_NOW -> "Press the shortcut now…"
    PreferencesText.SHORTCUT_CAPTURE_HELP -> "Press one supported key, optionally with Ctrl, Alt, Shift, or Meta. Escape cancels."
    PreferencesText.SHORTCUT_LISTENING_WHILE_ASSISTANT_OPEN -> "Listening while the AI Assistant window is open."
    PreferencesText.SHORTCUT_INACTIVE_ASSISTANT_CLOSED -> "The shortcut is inactive while the AI Assistant is closed."
    PreferencesText.SHORTCUT_UNAVAILABLE -> "Global Push-to-Talk is unavailable on this system."
    PreferencesText.SHORTCUT_MODIFIER_ONLY_INVALID -> "A modifier key alone cannot be used as a shortcut."
    PreferencesText.SHORTCUT_UNSUPPORTED_KEY -> "That key is not supported for Push-to-Talk."
    PreferencesText.VOICE_OUTPUT -> "Voice Output"
    PreferencesText.INPUT_PROVIDER -> "Input Provider"
    PreferencesText.OUTPUT_PROVIDER -> "Output Provider"
    PreferencesText.INPUT_LOCAL_HELP -> "Local: Audio stays on this computer."
    PreferencesText.INPUT_OPENAI_HELP -> "Audio is sent to OpenAI for transcription."
    PreferencesText.INPUT_ALIBABA_HELP -> "Audio is sent to Alibaba Cloud for transcription."
    PreferencesText.INPUT_OFF_HELP -> "Microphone recording is disabled."
    PreferencesText.OUTPUT_LOCAL_HELP -> "Local: Assistant text is read by the Windows speech engine."
    PreferencesText.OUTPUT_OPENAI_HELP -> "Assistant text is sent to OpenAI for speech synthesis."
    PreferencesText.OUTPUT_ALIBABA_HELP -> "Text is sent to Alibaba Cloud for speech synthesis."
    PreferencesText.OUTPUT_OFF_HELP -> "Speech playback is disabled."
    PreferencesText.OPTIONAL_SPEECH_PACK -> "Optional Speech Pack"
    PreferencesText.INSTALLED_MODEL -> "Installed: ${arguments[0]}"
    PreferencesText.LOCAL_SPEECH_MODEL_NOT_INSTALLED -> "Local speech model not installed."
    PreferencesText.REMOVE_SPEECH_PACK -> "Remove Speech Pack"
    PreferencesText.DOWNLOAD_SPEECH_PACK -> "Download Speech Pack"
    PreferencesText.STT_MODEL -> "STT Model"
    PreferencesText.TTS_MODEL -> "TTS Model"
    PreferencesText.VOICE -> "Voice"
    PreferencesText.REGION -> "Region"
    PreferencesText.WORKSPACE_ID -> "Workspace ID"
    PreferencesText.TEST_RECOGNITION -> "Test Recognition"
    PreferencesText.TESTING_RECOGNITION -> "Testing Recognition…"
    PreferencesText.TEST_VOICE -> "Test Voice"
    PreferencesText.TESTING_VOICE -> "Testing Voice…"
    PreferencesText.AUTO_SEND_AFTER_TRANSCRIPTION -> "Auto-send after transcription"
    PreferencesText.READ_ASSISTANT_REPLIES_ALOUD -> "Read assistant replies aloud"
    PreferencesText.WINDOWS_SPEECH -> "Windows Speech"
    PreferencesText.WINDOWS_VOICE -> "Windows Voice"
    PreferencesText.SYSTEM_DEFAULT -> "System default"
    PreferencesText.RATE -> "Rate: ${arguments[0]}"
    PreferencesText.VOLUME -> "Volume: ${arguments[0]}"
    PreferencesText.SAVE_VOICE_SETTINGS -> "Save Voice Settings"
    PreferencesText.DELETE_OPENAI_VOICE_KEY -> "Delete OpenAI Voice Key"
    PreferencesText.DELETE_ALIBABA_SPEECH_KEY -> "Delete Alibaba Speech Key"
    PreferencesText.ENTER_API_KEY -> "Enter API Key"
    PreferencesText.LEAVE_BLANK_TO_KEEP_KEY -> "Leave blank to keep current Key"
    PreferencesText.REPLACE_PROVIDER_API_KEY -> "Replace ${arguments[0]} API Key"
    PreferencesText.PROVIDER_API_KEY -> "${arguments[0]} API Key"
    PreferencesText.AI_PROVIDER -> "AI Provider"
    PreferencesText.AI_PROVIDER_LAZY_HELP -> "The provider is initialized only when you test the connection or send an AI message."
    PreferencesText.PROVIDER -> "Provider"
    PreferencesText.BASE_URL -> "Base URL"
    PreferencesText.MODEL -> "Model"
    PreferencesText.MODEL_ID_PLACEHOLDER -> "${arguments[0]} model ID"
    PreferencesText.OFFICIAL_PROVIDER_ENDPOINT -> "Uses the official ${arguments[0]} API endpoint."
    PreferencesText.API_KEY -> "API Key"
    PreferencesText.REPLACE_API_KEY -> "Replace API Key"
    PreferencesText.API_KEY_SAVED_SECURELY -> "API Key: Saved securely"
    PreferencesText.API_KEY_SESSION_ONLY -> "API Key: This session only — Key will not be saved"
    PreferencesText.CREDENTIAL_ENVIRONMENT_VARIABLE -> "Credential: Environment variable"
    PreferencesText.API_KEY_NOT_CONFIGURED -> "API Key: Not configured"
    PreferencesText.TIMEOUT_SECONDS -> "Timeout (seconds)"
    PreferencesText.TEMPERATURE -> "Temperature"
    PreferencesText.TEMPERATURE_REQUIRED -> "Temperature is required."
    PreferencesText.PROVIDER_SETTINGS_INVALID -> "Provider settings are invalid."
    PreferencesText.TEST_CONNECTION -> "Test Connection"
    PreferencesText.SAVE -> "Save"
    PreferencesText.DELETE_API_KEY -> "Delete API Key"
    PreferencesText.CONNECTION_TEST -> "Connection Test"
    PreferencesText.CONNECTION -> "Connection"
    PreferencesText.AUTHENTICATION -> "Authentication"
    PreferencesText.MODEL_CHECK -> "Model"
    PreferencesText.TOOL_CALLING -> "Tool Calling"
    PreferencesText.SEARCH_RESPONSE -> "Search response"
    PreferencesText.SOURCE_PARSING -> "Source parsing"
    PreferencesText.CHECK_PASSED -> "Passed"
    PreferencesText.CHECK_FAILED -> "Failed"
    PreferencesText.CHECK_NOT_RUN -> "Not tested"
    PreferencesText.API_CONNECTION_SUCCESSFUL -> "API connection successful"
    PreferencesText.MODEL_VALUE -> "Model: ${arguments[0]}"
    PreferencesText.TOOL_CALLING_SUPPORTED -> "Tool Calling supported"
    PreferencesText.MODEL_NOT_TESTED -> "Model was not tested"
    PreferencesText.TOOL_CALLING_NOT_TESTED -> "Tool Calling was not tested"
    PreferencesText.ENABLE_WEB_SEARCH -> "Enable Web Search"
    PreferencesText.WEB_SEARCH_PROVIDER -> "Provider: Brave Search"
    PreferencesText.WEB_SEARCH_HELP -> "Uses Brave LLM Context for current public information. Planner routes and map data stay local."
    PreferencesText.BRAVE_API_KEY -> "Brave API Key"
    PreferencesText.REPLACE_BRAVE_API_KEY -> "Replace Brave API Key"
    PreferencesText.ENTER_BRAVE_API_KEY -> "Enter Brave Search API Key"
    PreferencesText.BRAVE_API_KEY_SAVED_SECURELY -> "Brave API Key: Saved securely"
    PreferencesText.BRAVE_API_KEY_SESSION_ONLY -> "Brave API Key: This session only — Key will not be saved"
    PreferencesText.BRAVE_CREDENTIAL_ENVIRONMENT -> "Credential: BRAVE_SEARCH_API_KEY"
    PreferencesText.BRAVE_API_KEY_NOT_CONFIGURED -> "Brave API Key: Not configured"
    PreferencesText.TEST_SEARCH -> "Test Search"
    PreferencesText.SEARCH_TEST -> "Search Test"
    PreferencesText.WEB_PACK_HELP -> "Exports the validated static universe and currently enabled Ansiblex links for a Web client. Choose a parent directory; the app creates ${arguments[0]} inside it."
    PreferencesText.EXPORT_WEB_PACK -> "Export Web Pack"
    PreferencesText.EXPORTING -> "Exporting…"
    PreferencesText.WEB_PACK_READ_ONLY_HELP -> "The export is read-only and does not modify static.db or user.db."
    PreferencesText.WEB_PACK_WRITING -> "Validating and writing the Web Pack…"
    PreferencesText.WEB_PACK_EXPORT_FAILED -> "Web Pack export failed"
    PreferencesText.WEB_PACK_EXPORT_SUCCEEDED -> "Web Pack exported successfully"
    PreferencesText.SELECT_WEB_PACK_PARENT -> "Select parent directory for ${arguments[0]}"
    PreferencesText.EXPORT_HERE -> "Export Here"
    PreferencesText.FEATURE_PACK_CONTROLS_UNAVAILABLE -> "Feature Pack controls unavailable"
    PreferencesText.FEATURE_PACK_STATUS_UNAVAILABLE -> "This Pack could not provide its current status."
    PreferencesText.SYSTEMS_COUNT -> "Systems: ${arguments[0]}"
    PreferencesText.STARGATE_LINKS_COUNT -> "Stargate links: ${arguments[0]}"
    PreferencesText.REGIONS_COUNT -> "Regions: ${arguments[0]}"
    PreferencesText.CONSTELLATIONS_COUNT -> "Constellations: ${arguments[0]}"
    PreferencesText.ANSIBLEX_LINKS_COUNT -> "Ansiblex links: ${arguments[0]}"
    PreferencesText.PACK_SCHEMA -> "Pack schema: ${arguments[0]}"
    PreferencesText.PACK_VERSION -> "Pack version: ${arguments[0]}"
    PreferencesText.OUTPUT_PATH -> "Output: ${arguments[0]}"
    PreferencesText.SHARED_MAP_HELP -> "Connect to a Shared Map Server and keep its read-only marker snapshot synchronized."
    PreferencesText.SERVER_URL -> "Server URL"
    PreferencesText.DEVICE_NAME -> "Device name"
    PreferencesText.STATUS -> "Status: ${arguments[0]}"
    PreferencesText.DISMISS -> "Dismiss"
    PreferencesText.WORKSPACE -> "Workspace"
    PreferencesText.SELECT_WORKSPACE -> "Select Workspace"
    PreferencesText.ROLE -> "Role: ${arguments[0]}"
    PreferencesText.LAST_SYNC -> "Last sync: ${arguments[0]}"
    PreferencesText.NEVER -> "Never"
    PreferencesText.SHARED_MARKERS_COUNT -> "Shared markers: ${arguments[0]}"
    PreferencesText.REVISION -> "Revision: ${arguments[0]}"
    PreferencesText.CONNECT_WITH_INVITE -> "Connect with Invite…"
    PreferencesText.REFRESH_NOW -> "Refresh Now"
    PreferencesText.DISCONNECT -> "Disconnect"
    PreferencesText.MANAGE_MEMBERS -> "Manage Members…"
    PreferencesText.MEMBER_MANAGEMENT_ONLINE_ONLY -> "Member management is available only while Shared Map is online."
    PreferencesText.CONNECT_TO_SHARED_MAP -> "Connect to Shared Map"
    PreferencesText.ONE_TIME_INVITE -> "One-time invite"
    PreferencesText.INVITE_NOT_SAVED -> "The invite is used once and is not saved."
    PreferencesText.CONNECT -> "Connect"
    PreferencesText.SHARED_NOT_CONFIGURED -> "Not configured"
    PreferencesText.SHARED_CONNECTING -> "Connecting"
    PreferencesText.SHARED_CONNECTED -> "Connected"
    PreferencesText.SHARED_DEGRADED -> "Degraded — showing stale data"
    PreferencesText.SHARED_OFFLINE -> "Offline"
    PreferencesText.SHARED_AUTH_REQUIRED -> "Authentication required"
    PreferencesText.SHARED_ACCESS_REMOVED -> "Access removed"
    PreferencesText.SHARED_INCOMPATIBLE_SERVER -> "Incompatible server"
    PreferencesText.SHARED_DISCONNECTED -> "Disconnected"
    PreferencesText.MAP_OVERLAYS -> "Map Overlays"
    PreferencesText.OVERLAY_VISIBILITY_HELP -> "Visibility changes affect map presentation only. Feature Packs remain enabled."
    PreferencesText.NO_FEATURE_PACK_OVERLAYS -> "No Feature Pack overlays are currently available."
    PreferencesText.SOURCE -> "Source: ${arguments[0]}"
    PreferencesText.PROVIDER_DESCRIPTION -> "Provider: ${arguments[0]}"
    PreferencesText.ENABLE_ALL_OVERLAYS -> "Enable All Overlays"
    PreferencesText.REAL_3D_STARGATE_VISIBILITY -> "Real 3D Stargate Visibility"
    PreferencesText.REAL_3D_STARGATE_VISIBILITY_HELP -> "Controls normal stargate connection visibility in Real 3D mode."
    PreferencesText.FOCUSED_AND_ADJACENT_REGIONS -> "Focused Region + Adjacent Regions"
    PreferencesText.SOVEREIGNTY -> "Sovereignty"
    PreferencesText.SOVEREIGNTY_LOGO_EMPHASIS_ZOOM -> "Sovereignty Logo Emphasis Zoom"
    PreferencesText.SOVEREIGNTY_LOGO_HELP -> "Choose the zoom level where alliance logos transition between background watermarks and bright political-map emblems."
    PreferencesText.ENTER_RANGE -> "Enter ${arguments[0]}–${arguments[1]}."
    PreferencesText.FULL_MAP_RANGE_HELP -> "Full map range 0.01x–250x; 0.05x steps are recommended near overview zoom."
    PreferencesText.FEATURE_PACKS_HELP -> "Installed Packs are local to this Windows user. New Packs are disabled by default."
    PreferencesText.NO_FEATURE_PACKS -> "No Feature Packs are installed."
    PreferencesText.CURRENT_EVE_IDENTITY -> "Current EVE Identity"
    PreferencesText.CURRENT_EVE_IDENTITY_HELP -> "Choose which connected character represents you. Its alliance identity is used automatically when available."
    PreferencesText.NO_EVE_IDENTITIES -> "No EVE identities are available. Connect a character with an identity-capable ESI Pack."
    PreferencesText.EVE_IDENTITY_CORPORATION -> "Corporation: ${arguments[0]} [${arguments[1]}]"
    PreferencesText.EVE_IDENTITY_ALLIANCE -> "Alliance: ${arguments[0]} [${arguments[1]}]"
    PreferencesText.EVE_IDENTITY_NO_ALLIANCE -> "Alliance: none"
    PreferencesText.SELECT_EVE_IDENTITY -> "Use This Identity"
    PreferencesText.SELECTED_EVE_IDENTITY -> "Current Identity"
    PreferencesText.REFRESH_EVE_IDENTITIES -> "Refresh Identities"
    PreferencesText.REFRESHING_EVE_IDENTITIES -> "Refreshing EVE identities..."
    PreferencesText.ID -> "ID: ${arguments[0]}"
    PreferencesText.VERSION -> "Version: ${arguments[0]}"
    PreferencesText.PUBLISHER -> "Publisher: ${arguments[0]}"
    PreferencesText.PATH -> "Path: ${arguments[0]}"
    PreferencesText.UNAVAILABLE -> "Unavailable"
    PreferencesText.MISSING_PACK_JAR -> "Missing pack.jar"
    PreferencesText.INVALID_PACK -> "Invalid Pack"
    PreferencesText.INCOMPATIBLE -> "Incompatible"
    PreferencesText.ENABLED -> "Enabled"
    PreferencesText.DISABLED -> "Disabled"
    PreferencesText.CONTROLS -> "Controls"
    PreferencesText.DISABLE -> "Disable"
    PreferencesText.ENABLE -> "Enable"
    PreferencesText.REMOVE -> "Remove"
    PreferencesText.REMOVE_PACK_TITLE -> "Remove ${arguments[0]}?"
    PreferencesText.REMOVE_PACK_HELP -> "This deletes the installed Pack directory. Pack-owned data is retained."
    PreferencesText.CURRENT_ZOOM -> "Current Zoom"
    PreferencesText.CONSTELLATION_2D_ZOOM_THRESHOLD -> "2D Constellation Zoom Threshold"
    PreferencesText.SYSTEM_2D_ZOOM_THRESHOLD -> "2D System Zoom Threshold"
    PreferencesText.CONSTELLATION_3D_ZOOM_THRESHOLD -> "3D Constellation Zoom Threshold"
    PreferencesText.SYSTEM_3D_ZOOM_THRESHOLD -> "3D System Zoom Threshold"
    PreferencesText.RESET_MAP_DISPLAY -> "Reset Map Display"
    PreferencesText.REGION_PRIMARY_FONT_SIZE -> "Region Primary Font Size"
    PreferencesText.REGION_BACKGROUND_FONT_SIZE -> "Region Background Font Size"
    PreferencesText.REGION_BACKGROUND_ALPHA -> "Region Background Alpha"
    PreferencesText.CONSTELLATION_FONT_SIZE -> "Constellation Font Size"
    PreferencesText.SYSTEM_FONT_SIZE -> "System Font Size"
    PreferencesText.MARKER_SETTINGS -> "Marker Settings"
    PreferencesText.SHOW_LOCAL_MARKERS -> "Show Local Markers"
    PreferencesText.SHOW_SHARED_MARKERS -> "Show Shared Markers"
    PreferencesText.SHOW_LOCAL_MARKER_NAMES -> "Show Local Marker Names"
    PreferencesText.SAVED_MARKER_APPEARANCE -> "Saved Marker Appearance"
    PreferencesText.OUTER_RING_RADIUS -> "Outer Ring Radius"
    PreferencesText.OUTER_RING_LINE_WIDTH -> "Outer Ring Line Width"
    PreferencesText.GLOW -> "Glow"
    PreferencesText.GLOW_STRENGTH -> "Glow Strength"
    PreferencesText.RESET_MARKER -> "Reset Marker"
    PreferencesText.MINI_MAP_SETTINGS -> "Mini-map Settings"
    PreferencesText.MINI_MAP_HELP -> "Controls the compact character-following map. Changes apply immediately to an open Mini-map."
    PreferencesText.VISIBLE_RANGE -> "Visible range"
    PreferencesText.HOP_COUNT -> "${arguments[0]} ${if (arguments[0].toString() == "1") "hop" else "hops"}"
    PreferencesText.SHOW_ANSIBLEX_CONNECTIONS -> "Show Ansiblex connections"
    PreferencesText.MINI_MAP_ANSIBLEX_HELP -> "Shown on the Mini-map and counted as one hop in its visible range."
    PreferencesText.WINDOW_STYLE -> "Window style"
    PreferencesText.STANDARD -> "Standard"
    PreferencesText.HUD -> "HUD"
    PreferencesText.WINDOW_STYLE_HELP -> "HUD uses a borderless translucent surface; Standard keeps the normal Planner window frame."
    PreferencesText.INTERACTION -> "Interaction"
    PreferencesText.INTERACTIVE -> "Interactive"
    PreferencesText.HUD_LOCKED -> "HUD Locked"
    PreferencesText.RECOVERY_HOTKEY -> "Recovery hotkey: ${arguments[0]} · ${arguments[1]}"
    PreferencesText.HOTKEY_STARTING -> "starting"
    PreferencesText.HOTKEY_READY -> "ready"
    PreferencesText.HOTKEY_UNAVAILABLE -> "unavailable"
    PreferencesText.HOTKEY_UNSUPPORTED -> "unsupported"
    PreferencesText.HOTKEY_STOPPED -> "stopped"
    PreferencesText.HUD_OPACITY -> "HUD opacity: ${arguments[0]}%"
    PreferencesText.SNAP_TO_SCREEN_EDGES -> "Snap to screen edges"
    PreferencesText.RESET_MINI_MAP -> "Reset Mini-map"
    PreferencesText.MCP_SERVER_PERMISSIONS -> "MCP Server & Permissions"
    PreferencesText.ENABLE_MCP_INTEGRATION -> "Enable MCP Integration"
    PreferencesText.ALLOW_AI_SAVED_MARKERS -> "Allow AI to access saved markers"
    PreferencesText.AI_SAVED_MARKERS_HELP -> "Allows AI tools to read and create saved markers. AI cannot modify or delete existing saved markers."
    PreferencesText.MCP_STARTING -> "Starting…"
    PreferencesText.MCP_LISTENING -> "Listening on localhost"
    PreferencesText.MCP_ALREADY_ACTIVE -> "Already Active in another app instance"
    PreferencesText.MCP_SESSION_HELP -> "When enabled, a new authenticated local-only control session starts after the map is ready."
    PreferencesText.RESET_MCP_INTEGRATION -> "Reset MCP Integration"
}
