package dev.evestaticmapplanner.localization.zhcn

import dev.evestaticmapplanner.localization.PreferencesText

internal fun chinesePreferenceText(id: PreferencesText, arguments: Array<out Any>): String = when (id) {
    PreferencesText.RESET_ALL -> "重置所有设置"
    PreferencesText.CATEGORY_MAP_DISPLAY, PreferencesText.MAP_DISPLAY -> "地图显示"
    PreferencesText.CATEGORY_AI_FEATURES -> "AI 功能"
    PreferencesText.CATEGORY_FEATURE_PACKS, PreferencesText.FEATURE_PACKS -> "功能包"
    PreferencesText.CATEGORY_OVERLAYS -> "叠加层"
    PreferencesText.CATEGORY_WEB_PACK, PreferencesText.WEB_PACK -> "Web 数据包"
    PreferencesText.CATEGORY_SHARED_MAP, PreferencesText.SHARED_MAP -> "共享地图"
    PreferencesText.EMBEDDED_ASSISTANT -> "内置 AI 助手"
    PreferencesText.AI_MODEL -> "AI 模型"
    PreferencesText.WEB_SEARCH -> "网页搜索"
    PreferencesText.VOICE_IO -> "语音输入/输出"
    PreferencesText.MCP_INTEGRATION -> "MCP 集成"
    PreferencesText.VOICE_INPUT -> "语音输入"
    PreferencesText.VOICE_OUTPUT -> "语音输出"
    PreferencesText.INPUT_PROVIDER -> "输入提供商"
    PreferencesText.OUTPUT_PROVIDER -> "输出提供商"
    PreferencesText.INPUT_LOCAL_HELP -> "本地：音频保留在此电脑上。"
    PreferencesText.INPUT_OPENAI_HELP -> "音频会发送到 OpenAI 进行识别。"
    PreferencesText.INPUT_ALIBABA_HELP -> "音频会发送到 Alibaba Cloud 进行识别。"
    PreferencesText.INPUT_OFF_HELP -> "麦克风录音已关闭。"
    PreferencesText.OUTPUT_LOCAL_HELP -> "本地：使用 Windows 语音引擎朗读助手文本。"
    PreferencesText.OUTPUT_OPENAI_HELP -> "助手文本会发送到 OpenAI 进行语音合成。"
    PreferencesText.OUTPUT_ALIBABA_HELP -> "文本会发送到 Alibaba Cloud 进行语音合成。"
    PreferencesText.OUTPUT_OFF_HELP -> "语音播放已关闭。"
    PreferencesText.OPTIONAL_SPEECH_PACK -> "可选语音包"
    PreferencesText.INSTALLED_MODEL -> "已安装：${arguments[0]}"
    PreferencesText.LOCAL_SPEECH_MODEL_NOT_INSTALLED -> "尚未安装本地语音模型。"
    PreferencesText.REMOVE_SPEECH_PACK -> "移除语音包"
    PreferencesText.DOWNLOAD_SPEECH_PACK -> "下载语音包"
    PreferencesText.STT_MODEL -> "识别模型"
    PreferencesText.TTS_MODEL -> "语音合成模型"
    PreferencesText.VOICE -> "音色"
    PreferencesText.REGION -> "区域"
    PreferencesText.WORKSPACE_ID -> "Workspace ID"
    PreferencesText.TEST_RECOGNITION -> "测试识别"
    PreferencesText.TESTING_RECOGNITION -> "正在测试识别……"
    PreferencesText.TEST_VOICE -> "测试语音"
    PreferencesText.TESTING_VOICE -> "正在测试语音……"
    PreferencesText.AUTO_SEND_AFTER_TRANSCRIPTION -> "识别后自动发送"
    PreferencesText.READ_ASSISTANT_REPLIES_ALOUD -> "朗读助手回复"
    PreferencesText.WINDOWS_SPEECH -> "Windows Speech"
    PreferencesText.WINDOWS_VOICE -> "Windows 音色"
    PreferencesText.SYSTEM_DEFAULT -> "系统默认"
    PreferencesText.RATE -> "语速：${arguments[0]}"
    PreferencesText.VOLUME -> "音量：${arguments[0]}"
    PreferencesText.SAVE_VOICE_SETTINGS -> "保存语音设置"
    PreferencesText.DELETE_OPENAI_VOICE_KEY -> "删除 OpenAI Voice Key"
    PreferencesText.DELETE_ALIBABA_SPEECH_KEY -> "删除 Alibaba Speech Key"
    PreferencesText.ENTER_API_KEY -> "输入 API Key"
    PreferencesText.LEAVE_BLANK_TO_KEEP_KEY -> "留空以保留当前 Key"
    PreferencesText.REPLACE_PROVIDER_API_KEY -> "替换 ${arguments[0]} API Key"
    PreferencesText.PROVIDER_API_KEY -> "${arguments[0]} API Key"
    PreferencesText.AI_PROVIDER -> "AI 提供商"
    PreferencesText.AI_PROVIDER_LAZY_HELP -> "仅在测试连接或发送 AI 消息时初始化提供商。"
    PreferencesText.PROVIDER -> "提供商"
    PreferencesText.BASE_URL -> "Base URL"
    PreferencesText.MODEL -> "模型"
    PreferencesText.MODEL_ID_PLACEHOLDER -> "${arguments[0]} 模型 ID"
    PreferencesText.OFFICIAL_PROVIDER_ENDPOINT -> "使用 ${arguments[0]} 官方 API 端点。"
    PreferencesText.API_KEY -> "API Key"
    PreferencesText.REPLACE_API_KEY -> "替换 API Key"
    PreferencesText.API_KEY_SAVED_SECURELY -> "API Key：已安全保存"
    PreferencesText.API_KEY_SESSION_ONLY -> "API Key：仅本次会话，不会保存"
    PreferencesText.CREDENTIAL_ENVIRONMENT_VARIABLE -> "凭据：环境变量"
    PreferencesText.API_KEY_NOT_CONFIGURED -> "API Key：未配置"
    PreferencesText.TIMEOUT_SECONDS -> "超时（秒）"
    PreferencesText.TEMPERATURE -> "温度"
    PreferencesText.TEMPERATURE_REQUIRED -> "必须填写温度。"
    PreferencesText.PROVIDER_SETTINGS_INVALID -> "提供商设置无效。"
    PreferencesText.TEST_CONNECTION -> "测试连接"
    PreferencesText.SAVE -> "保存"
    PreferencesText.DELETE_API_KEY -> "删除 API Key"
    PreferencesText.CONNECTION_TEST -> "连接测试"
    PreferencesText.CONNECTION -> "连接"
    PreferencesText.AUTHENTICATION -> "身份验证"
    PreferencesText.MODEL_CHECK -> "模型"
    PreferencesText.TOOL_CALLING -> "工具调用"
    PreferencesText.SEARCH_RESPONSE -> "搜索响应"
    PreferencesText.SOURCE_PARSING -> "来源解析"
    PreferencesText.CHECK_PASSED -> "通过"
    PreferencesText.CHECK_FAILED -> "失败"
    PreferencesText.CHECK_NOT_RUN -> "未测试"
    PreferencesText.API_CONNECTION_SUCCESSFUL -> "API 连接成功"
    PreferencesText.MODEL_VALUE -> "模型：${arguments[0]}"
    PreferencesText.TOOL_CALLING_SUPPORTED -> "支持工具调用"
    PreferencesText.MODEL_NOT_TESTED -> "未测试模型"
    PreferencesText.TOOL_CALLING_NOT_TESTED -> "未测试工具调用"
    PreferencesText.ENABLE_WEB_SEARCH -> "启用网页搜索"
    PreferencesText.WEB_SEARCH_PROVIDER -> "提供商：Brave Search"
    PreferencesText.WEB_SEARCH_HELP -> "使用 Brave LLM Context 获取当前公开信息。规划器路线和地图数据仍保留在本地。"
    PreferencesText.BRAVE_API_KEY -> "Brave API Key"
    PreferencesText.REPLACE_BRAVE_API_KEY -> "替换 Brave API Key"
    PreferencesText.ENTER_BRAVE_API_KEY -> "输入 Brave Search API Key"
    PreferencesText.BRAVE_API_KEY_SAVED_SECURELY -> "Brave API Key：已安全保存"
    PreferencesText.BRAVE_API_KEY_SESSION_ONLY -> "Brave API Key：仅本次会话，不会保存"
    PreferencesText.BRAVE_CREDENTIAL_ENVIRONMENT -> "凭据：BRAVE_SEARCH_API_KEY"
    PreferencesText.BRAVE_API_KEY_NOT_CONFIGURED -> "Brave API Key：未配置"
    PreferencesText.TEST_SEARCH -> "测试搜索"
    PreferencesText.SEARCH_TEST -> "搜索测试"
    PreferencesText.WEB_PACK_HELP -> "导出已验证的静态宇宙数据和当前启用的 Ansiblex 连接，供 Web 客户端使用。请选择父目录；应用会在其中创建 ${arguments[0]}。"
    PreferencesText.EXPORT_WEB_PACK -> "导出 Web 数据包"
    PreferencesText.EXPORTING -> "正在导出……"
    PreferencesText.WEB_PACK_READ_ONLY_HELP -> "导出为只读操作，不会修改 static.db 或 user.db。"
    PreferencesText.WEB_PACK_WRITING -> "正在验证并写入 Web 数据包……"
    PreferencesText.WEB_PACK_EXPORT_FAILED -> "Web 数据包导出失败"
    PreferencesText.WEB_PACK_EXPORT_SUCCEEDED -> "Web 数据包导出成功"
    PreferencesText.SYSTEMS_COUNT -> "星系：${arguments[0]}"
    PreferencesText.STARGATE_LINKS_COUNT -> "星门连接：${arguments[0]}"
    PreferencesText.REGIONS_COUNT -> "星域：${arguments[0]}"
    PreferencesText.CONSTELLATIONS_COUNT -> "星座：${arguments[0]}"
    PreferencesText.ANSIBLEX_LINKS_COUNT -> "Ansiblex 连接：${arguments[0]}"
    PreferencesText.PACK_SCHEMA -> "数据包 schema：${arguments[0]}"
    PreferencesText.PACK_VERSION -> "数据包版本：${arguments[0]}"
    PreferencesText.OUTPUT_PATH -> "输出：${arguments[0]}"
    PreferencesText.SHARED_MAP_HELP -> "连接共享地图服务器，并保持只读标记快照同步。"
    PreferencesText.SERVER_URL -> "服务器 URL"
    PreferencesText.DEVICE_NAME -> "设备名称"
    PreferencesText.STATUS -> "状态：${arguments[0]}"
    PreferencesText.DISMISS -> "关闭提示"
    PreferencesText.WORKSPACE -> "工作区"
    PreferencesText.SELECT_WORKSPACE -> "选择工作区"
    PreferencesText.ROLE -> "角色：${arguments[0]}"
    PreferencesText.LAST_SYNC -> "上次同步：${arguments[0]}"
    PreferencesText.NEVER -> "从未"
    PreferencesText.SHARED_MARKERS_COUNT -> "共享标记：${arguments[0]}"
    PreferencesText.REVISION -> "修订版本：${arguments[0]}"
    PreferencesText.CONNECT_WITH_INVITE -> "使用邀请连接……"
    PreferencesText.REFRESH_NOW -> "立即刷新"
    PreferencesText.DISCONNECT -> "断开连接"
    PreferencesText.MANAGE_MEMBERS -> "管理成员……"
    PreferencesText.MEMBER_MANAGEMENT_ONLINE_ONLY -> "仅当共享地图在线时才能管理成员。"
    PreferencesText.CONNECT_TO_SHARED_MAP -> "连接共享地图"
    PreferencesText.ONE_TIME_INVITE -> "一次性邀请"
    PreferencesText.INVITE_NOT_SAVED -> "邀请仅使用一次，不会保存。"
    PreferencesText.CONNECT -> "连接"
    PreferencesText.SHARED_NOT_CONFIGURED -> "未配置"
    PreferencesText.SHARED_CONNECTING -> "正在连接"
    PreferencesText.SHARED_CONNECTED -> "已连接"
    PreferencesText.SHARED_DEGRADED -> "服务降级——正在显示旧数据"
    PreferencesText.SHARED_OFFLINE -> "离线"
    PreferencesText.SHARED_AUTH_REQUIRED -> "需要身份验证"
    PreferencesText.SHARED_ACCESS_REMOVED -> "访问权限已移除"
    PreferencesText.SHARED_INCOMPATIBLE_SERVER -> "服务器不兼容"
    PreferencesText.SHARED_DISCONNECTED -> "已断开"
    PreferencesText.MAP_OVERLAYS -> "地图叠加层"
    PreferencesText.OVERLAY_VISIBILITY_HELP -> "可见性更改仅影响地图显示，功能包仍保持启用。"
    PreferencesText.NO_FEATURE_PACK_OVERLAYS -> "当前没有可用的功能包叠加层。"
    PreferencesText.SOURCE -> "来源：${arguments[0]}"
    PreferencesText.PROVIDER_DESCRIPTION -> "提供商：${arguments[0]}"
    PreferencesText.ENABLE_ALL_OVERLAYS -> "启用所有叠加层"
    PreferencesText.REAL_3D_STARGATE_VISIBILITY -> "Real 3D 星门可见性"
    PreferencesText.REAL_3D_STARGATE_VISIBILITY_HELP -> "控制 Real 3D 模式中普通星门连接的可见性。"
    PreferencesText.FOCUSED_AND_ADJACENT_REGIONS -> "聚焦星域及相邻星域"
    PreferencesText.SOVEREIGNTY -> "主权"
    PreferencesText.SOVEREIGNTY_LOGO_EMPHASIS_ZOOM -> "主权标志强调缩放级别"
    PreferencesText.SOVEREIGNTY_LOGO_HELP -> "选择联盟标志从背景水印切换为明亮政治地图徽标的缩放级别。"
    PreferencesText.ENTER_RANGE -> "请输入 ${arguments[0]}–${arguments[1]}。"
    PreferencesText.FULL_MAP_RANGE_HELP -> "完整地图范围为 0.01x–250x；总览附近建议使用 0.05x 步长。"
    PreferencesText.FEATURE_PACKS_HELP -> "已安装的功能包仅供当前 Windows 用户使用。新功能包默认禁用。"
    PreferencesText.NO_FEATURE_PACKS -> "未安装功能包。"
    PreferencesText.ID -> "ID：${arguments[0]}"
    PreferencesText.VERSION -> "版本：${arguments[0]}"
    PreferencesText.PUBLISHER -> "发布者：${arguments[0]}"
    PreferencesText.PATH -> "路径：${arguments[0]}"
    PreferencesText.UNAVAILABLE -> "不可用"
    PreferencesText.MISSING_PACK_JAR -> "缺少 pack.jar"
    PreferencesText.INVALID_PACK -> "功能包无效"
    PreferencesText.INCOMPATIBLE -> "不兼容"
    PreferencesText.ENABLED -> "已启用"
    PreferencesText.DISABLED -> "已禁用"
    PreferencesText.CONTROLS -> "控制项"
    PreferencesText.DISABLE -> "禁用"
    PreferencesText.ENABLE -> "启用"
    PreferencesText.REMOVE -> "移除"
    PreferencesText.REMOVE_PACK_TITLE -> "移除 ${arguments[0]}？"
    PreferencesText.REMOVE_PACK_HELP -> "这会删除已安装的功能包目录，但保留功能包拥有的数据。"
    PreferencesText.CURRENT_ZOOM -> "当前缩放"
    PreferencesText.CONSTELLATION_2D_ZOOM_THRESHOLD -> "2D 星座缩放阈值"
    PreferencesText.SYSTEM_2D_ZOOM_THRESHOLD -> "2D 星系缩放阈值"
    PreferencesText.CONSTELLATION_3D_ZOOM_THRESHOLD -> "3D 星座缩放阈值"
    PreferencesText.SYSTEM_3D_ZOOM_THRESHOLD -> "3D 星系缩放阈值"
    PreferencesText.RESET_MAP_DISPLAY -> "重置地图显示"
    PreferencesText.REGION_PRIMARY_FONT_SIZE -> "星域主标签字号"
    PreferencesText.REGION_BACKGROUND_FONT_SIZE -> "星域背景标签字号"
    PreferencesText.REGION_BACKGROUND_ALPHA -> "星域背景透明度"
    PreferencesText.CONSTELLATION_FONT_SIZE -> "星座字号"
    PreferencesText.SYSTEM_FONT_SIZE -> "星系字号"
    PreferencesText.MARKER_SETTINGS -> "标记设置"
    PreferencesText.SHOW_LOCAL_MARKERS -> "显示本地标记"
    PreferencesText.SHOW_SHARED_MARKERS -> "显示共享标记"
    PreferencesText.SHOW_LOCAL_MARKER_NAMES -> "显示本地标记名称"
    PreferencesText.SAVED_MARKER_APPEARANCE -> "已保存标记外观"
    PreferencesText.OUTER_RING_RADIUS -> "外环半径"
    PreferencesText.OUTER_RING_LINE_WIDTH -> "外环线宽"
    PreferencesText.GLOW -> "发光"
    PreferencesText.GLOW_STRENGTH -> "发光强度"
    PreferencesText.RESET_MARKER -> "重置标记设置"
    PreferencesText.MINI_MAP_SETTINGS -> "小地图设置"
    PreferencesText.MINI_MAP_HELP -> "控制跟随角色的紧凑地图。更改会立即应用到已打开的小地图。"
    PreferencesText.VISIBLE_RANGE -> "可见范围"
    PreferencesText.HOP_COUNT -> "${arguments[0]} 跳"
    PreferencesText.SHOW_ANSIBLEX_CONNECTIONS -> "显示 Ansiblex 连接"
    PreferencesText.MINI_MAP_ANSIBLEX_HELP -> "在小地图上显示，并在可见范围内按一跳计算。"
    PreferencesText.WINDOW_STYLE -> "窗口样式"
    PreferencesText.STANDARD -> "标准"
    PreferencesText.HUD -> "HUD"
    PreferencesText.WINDOW_STYLE_HELP -> "HUD 使用无边框半透明界面；标准模式保留规划器普通窗口边框。"
    PreferencesText.INTERACTION -> "交互"
    PreferencesText.INTERACTIVE -> "可交互"
    PreferencesText.HUD_LOCKED -> "HUD 锁定"
    PreferencesText.RECOVERY_HOTKEY -> "恢复快捷键：${arguments[0]} · ${arguments[1]}"
    PreferencesText.HOTKEY_STARTING -> "正在启动"
    PreferencesText.HOTKEY_READY -> "就绪"
    PreferencesText.HOTKEY_UNAVAILABLE -> "不可用"
    PreferencesText.HOTKEY_UNSUPPORTED -> "不支持"
    PreferencesText.HOTKEY_STOPPED -> "已停止"
    PreferencesText.HUD_OPACITY -> "HUD 不透明度：${arguments[0]}%"
    PreferencesText.SNAP_TO_SCREEN_EDGES -> "吸附到屏幕边缘"
    PreferencesText.RESET_MINI_MAP -> "重置小地图"
    PreferencesText.MCP_SERVER_PERMISSIONS -> "MCP 服务器与权限"
    PreferencesText.ENABLE_MCP_INTEGRATION -> "启用 MCP 集成"
    PreferencesText.ALLOW_AI_SAVED_MARKERS -> "允许 AI 访问已保存标记"
    PreferencesText.AI_SAVED_MARKERS_HELP -> "允许 AI 工具读取和创建已保存标记。AI 无法修改或删除现有标记。"
    PreferencesText.MCP_STARTING -> "正在启动……"
    PreferencesText.MCP_LISTENING -> "正在 localhost 监听"
    PreferencesText.MCP_ALREADY_ACTIVE -> "另一个应用实例已在运行"
    PreferencesText.MCP_SESSION_HELP -> "启用后，地图就绪时会启动新的、经过身份验证且仅限本机的控制会话。"
    PreferencesText.RESET_MCP_INTEGRATION -> "重置 MCP 集成"
}
